[package]
name = "glfw-bindings"
version = "0.1.0"
edition = "2024"

[build-dependencies]
bindgen = "0.71.1"

[dependencies]
ffi-utils = { path = "../ffi-utils" }
vulkan-bindings = { path = "../vulkan-bindings" }

[lib]
path = "src/lib.rs"
